import Foundation

func makeMethodName(from key: String) -> String {
    let cleaned = key
        .replacingOccurrences(of: "[^a-zA-Z0-9]", with: "_", options: .regularExpression)
        .replacingOccurrences(of: "_+", with: "_", options: .regularExpression)
        .trimmingCharacters(in: CharacterSet(charactersIn: "_"))
    if let first = cleaned.first, first.isUppercase {
        return String(first).lowercased() + cleaned.dropFirst()
    }
    return cleaned.isEmpty ? "key" : cleaned
}

func countPercentSpecifiers(_ value: String) -> (at: Int, lld: Int) {
    var at = 0, lld = 0
    let chars = Array(value)
    var i = 0
    while i < chars.count {
        if chars[i] == "%" && i + 1 < chars.count {
            if chars[i + 1] == "@" {
                at += 1
                i += 1
            } else if chars[i + 1] == "l" && i + 3 < chars.count
                        && chars[i + 2] == "l" && chars[i + 3] == "d" {
                lld += 1
                i += 3
            }
        }
        i += 1
    }
    return (at, lld)
}

guard CommandLine.arguments.count >= 2 else {
    fputs("error: Usage: \(CommandLine.arguments[0]) <path-to-xcstrings>\n", stderr)
    exit(1)
}

let xcstringsPath = CommandLine.arguments[1]
let table = URL(fileURLWithPath: xcstringsPath).deletingPathExtension().lastPathComponent

let data = try Data(contentsOf: URL(fileURLWithPath: xcstringsPath))
let json = try JSONSerialization.jsonObject(with: data) as! [String: Any]
let strings = json["strings"] as! [String: Any]

var errors: [String] = []
var warnings: [String] = []

for key in strings.keys.sorted() {
    guard !key.isEmpty, key != "%@", key != "%lld" else { continue }

    guard let entry = strings[key] as? [String: Any] else {
        errors.append("error: '\(key)': entry is not a valid object")
        continue
    }

    let localizations = entry["localizations"] as? [String: Any] ?? [:]
    let enEntry = localizations["en"] as? [String: Any]
    let stringUnit = enEntry?["stringUnit"] as? [String: Any]
    let value = stringUnit?["value"] as? String

    if value == nil {
        errors.append("error: '\(key)': missing English (en) localization value")
        continue
    }

    let nonEnglishKeys = localizations.keys.filter { $0 != "en" && !$0.isEmpty }
    if !nonEnglishKeys.isEmpty {
        warnings.append("warning: '\(key)': has non-English localizations (\(nonEnglishKeys.joined(separator: ", "))). All keys should be English-only.")
    }
}

for warning in warnings {
    fputs("\(warning)\n", stderr)
}

if !errors.isEmpty {
    for error in errors {
        fputs("\(error)\n", stderr)
    }
    exit(1)
}

let dateFormatter = DateFormatter()
dateFormatter.dateFormat = "yyyy-MM-dd HH:mm:ss"
let dateStr = dateFormatter.string(from: Date())

var lines = [
    "// Generated by GenerateLocalization on \(dateStr)",
    "// Do not edit manually. Re-run: swift Packages/SingleCalendarFeature/Sources/GenerateLocalization/main.swift <path-to-xcstrings>",
    "",
    "import SwiftUI",
    "",
    "extension LocalizedStringKey {"
]
var usedNames = Set<String>()

for key in strings.keys.sorted() {
    guard !key.isEmpty, key != "%@", key != "%lld" else { continue }

    guard let entry = strings[key] as? [String: Any],
          let localizations = entry["localizations"] as? [String: Any],
          let enEntry = localizations["en"] as? [String: Any],
          let stringUnit = enEntry["stringUnit"] as? [String: Any],
          let value = stringUnit["value"] as? String else { continue }

    let specifiers = countPercentSpecifiers(value)
    let numArgs = specifiers.at + specifiers.lld

    let baseName = makeMethodName(from: key)
    var methodName = baseName
    var counter = 1
    while usedNames.contains(methodName) {
        methodName = "\(baseName)\(counter)"
        counter += 1
    }
    usedNames.insert(methodName)

    let escaped = key.replacingOccurrences(of: "\\", with: "\\\\").replacingOccurrences(of: "\"", with: "\\\"")

    if numArgs == 0 {
        lines.append("    static let \(methodName) = LocalizedStringKey(\"\(escaped)\")")
    } else {
        var argNames: [String] = []
        if let comment = (entry["comment"] as? String)?.lowercased() {
            if comment.contains("name") || comment.contains("calendar") { argNames.append("name") }
            if comment.contains("time") || comment.contains("date") { argNames.append("time") }
            if comment.contains("number") || comment.contains("count") || comment.contains("column") { argNames.append("count") }
        }
        while argNames.count < numArgs {
            argNames.append("arg\(argNames.count)")
        }

        let params = argNames.prefix(numArgs).map { "_ \($0): CVarArg" }.joined(separator: ", ")
        let args = argNames.prefix(numArgs).joined(separator: ", ")
        lines.append("    static func \(methodName)(\(params)) -> LocalizedStringKey {")
        lines.append("        let format = NSLocalizedString(\"\(escaped)\", tableName: \"\(table)\", bundle: .module, comment: \"\")")
        lines.append("        return LocalizedStringKey(String(format: format, \(args)))")
        lines.append("    }")
    }
}

lines.append("}")
lines.append("")

let output = lines.joined(separator: "\n")
let outputPath = URL(fileURLWithPath: xcstringsPath)
    .deletingLastPathComponent()
    .deletingLastPathComponent()
    .appendingPathComponent("LocalizedStringKeyExtension.swift")

try output.write(toFile: outputPath.path, atomically: true, encoding: .utf8)
print("Generated \(usedNames.count) static members at: \(outputPath.path)")
