// Generated by GenerateLocalization on 2026-08-28 19:24:42
// Do not edit manually. Re-run: swift Packages/SingleCalendarFeature/Sources/GenerateLocalization/main.swift <path-to-xcstrings>

import SwiftUI

extension LocalizedStringKey {
    static let archive = LocalizedStringKey("Archive")
    static let archived = LocalizedStringKey("Archived")
    static let calendar_name = LocalizedStringKey("Calendar name")
    static let calendars = LocalizedStringKey("Calendars")
    static let choose_a_calendar_from_the_list = LocalizedStringKey("Choose a calendar from the list")
    static let close = LocalizedStringKey("Close")
    static func columns_lld(_ name: CVarArg) -> LocalizedStringKey {
        let format = NSLocalizedString("Columns: %lld", tableName: "pcScfLocalisation", bundle: .module, comment: "")
        return LocalizedStringKey(String(format: format, name))
    }
    static let delete_Permanently = LocalizedStringKey("Delete Permanently")
    static let edit = LocalizedStringKey("Edit")
    static let edit_calendar = LocalizedStringKey("Edit calendar")
    static let enter_calendar_name = LocalizedStringKey("Enter calendar name")
    static let enter_event_time = LocalizedStringKey("Enter event time")
    static let enter_name = LocalizedStringKey("Enter name")
    static let enter_your_email = LocalizedStringKey("Enter your email")
    static let enter_your_password = LocalizedStringKey("Enter your password")
    static let events = LocalizedStringKey("Events")
    static func greetings(_ arg0: CVarArg) -> LocalizedStringKey {
        let format = NSLocalizedString("Greetings, %@!", tableName: "pcScfLocalisation", bundle: .module, comment: "")
        return LocalizedStringKey(String(format: format, arg0))
    }
    static let loading = LocalizedStringKey("Loading")
    static let menu = LocalizedStringKey("Menu")
    static let multiselect = LocalizedStringKey("Multiselect")
    static let my_calendars = LocalizedStringKey("My calendars")
    static let name = LocalizedStringKey("Name")
    static let no_archived_calendars = LocalizedStringKey("No archived calendars")
    static let no_calendar_press_to_add = LocalizedStringKey("No calendar, press “+” to add")
    static let pinCal = LocalizedStringKey("PinCal")
    static let restore = LocalizedStringKey("Restore")
    static let save = LocalizedStringKey("Save")
    static let select_a_calendar = LocalizedStringKey("Select a calendar")
    static let select_color = LocalizedStringKey("Select color")
    static let sign_In = LocalizedStringKey("Sign In")
    static let slide_in = LocalizedStringKey("Slide in")
    static func at(_ time: CVarArg) -> LocalizedStringKey {
        let format = NSLocalizedString("at %@", tableName: "pcScfLocalisation", bundle: .module, comment: "")
        return LocalizedStringKey(String(format: format, time))
    }
    static func eventAt(_ arg0: CVarArg, _ arg1: CVarArg) -> LocalizedStringKey {
        let format = NSLocalizedString("eventAt", tableName: "pcScfLocalisation", bundle: .module, comment: "")
        return LocalizedStringKey(String(format: format, arg0, arg1))
    }
}
