// Generated by GenerateLocalization on 2026-09-05 20:50:00
// Do not edit manually. Re-run: swift Packages/SingleCalendarFeature/Sources/GenerateLocalization/main.swift <path-to-xcstrings>

import SwiftUI

extension LocalizedStringKey {
    static var archive: LocalizedStringKey { LocalizedStringKey("Archive") }
    static var archived: LocalizedStringKey { LocalizedStringKey("Archived") }
    static var calendar_name: LocalizedStringKey { LocalizedStringKey("Calendar name") }
    static var calendars: LocalizedStringKey { LocalizedStringKey("Calendars") }
    static var choose_a_calendar_from_the_list: LocalizedStringKey { LocalizedStringKey("Choose a calendar from the list") }
    static var close: LocalizedStringKey { LocalizedStringKey("Close") }
    static func columns_lld(_ name: CVarArg) -> LocalizedStringKey {
        let format = NSLocalizedString("Columns: %lld", tableName: "pcScfLocalisation", bundle: .module, comment: "")
        return LocalizedStringKey(String(format: format, name))
    }
    static var delete_Permanently: LocalizedStringKey { LocalizedStringKey("Delete Permanently") }
    static var edit: LocalizedStringKey { LocalizedStringKey("Edit") }
    static var edit_calendar: LocalizedStringKey { LocalizedStringKey("Edit calendar") }
    static var enter_calendar_name: LocalizedStringKey { LocalizedStringKey("Enter calendar name") }
    static var enter_event_time: LocalizedStringKey { LocalizedStringKey("Enter event time") }
    static var enter_name: LocalizedStringKey { LocalizedStringKey("Enter name") }
    static var enter_your_email: LocalizedStringKey { LocalizedStringKey("Enter your email") }
    static var enter_your_password: LocalizedStringKey { LocalizedStringKey("Enter your password") }
    static var events: LocalizedStringKey { LocalizedStringKey("Events") }
    static func greetings(_ arg0: CVarArg) -> LocalizedStringKey {
        let format = NSLocalizedString("Greetings, %@!", tableName: "pcScfLocalisation", bundle: .module, comment: "")
        return LocalizedStringKey(String(format: format, arg0))
    }
    static var loading: LocalizedStringKey { LocalizedStringKey("Loading") }
    static var menu: LocalizedStringKey { LocalizedStringKey("Menu") }
    static var multiselect: LocalizedStringKey { LocalizedStringKey("Multiselect") }
    static var my_calendars: LocalizedStringKey { LocalizedStringKey("My calendars") }
    static var name: LocalizedStringKey { LocalizedStringKey("Name") }
    static var no_archived_calendars: LocalizedStringKey { LocalizedStringKey("No archived calendars") }
    static var no_calendar_press_to_add: LocalizedStringKey { LocalizedStringKey("No calendar, press “+” to add") }
    static var pinCal: LocalizedStringKey { LocalizedStringKey("PinCal") }
    static var restore: LocalizedStringKey { LocalizedStringKey("Restore") }
    static var save: LocalizedStringKey { LocalizedStringKey("Save") }
    static var select_a_calendar: LocalizedStringKey { LocalizedStringKey("Select a calendar") }
    static var select_color: LocalizedStringKey { LocalizedStringKey("Select color") }
    static var sign_In: LocalizedStringKey { LocalizedStringKey("Sign In") }
    static var slide_in: LocalizedStringKey { LocalizedStringKey("Slide in") }
    static func at(_ time: CVarArg) -> LocalizedStringKey {
        let format = NSLocalizedString("at %@", tableName: "pcScfLocalisation", bundle: .module, comment: "")
        return LocalizedStringKey(String(format: format, time))
    }
    static func eventAt(_ arg0: CVarArg, _ arg1: CVarArg) -> LocalizedStringKey {
        let format = NSLocalizedString("eventAt", tableName: "pcScfLocalisation", bundle: .module, comment: "")
        return LocalizedStringKey(String(format: format, arg0, arg1))
    }
}
